remote_theme: just-the-docs/just-the-docs@v0.4.2
color_scheme: dark
title: The Gitrog Docs
permalink: pretty
exclude: ["CNAME", "readme.md"]

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
#  "GitHub":
#   - "//github.com/thegitrogserver/thegitrogserver.github.io"
  "The List":
    - "//moxfield.com/decks/4fbiNVFpr0edHL5Y3IKecg"
  "Discord":
    - "//discord.gg/4EgSfKX"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

footer_content: "The content on this page is in the commons of the mind—invented by many group discussions—and is provided publicly for the betterment of the Magic community. If you live in a dystopian hell like Germany or India then consider this content as being distributed under the <a href=\"https://creativecommons.org/publicdomain/zero/1.0/legalcode\">Creative Commons Zero (CC0)</a> license or some other public-domain-equivalent license recognized in your country."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%F %R" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/thegitrogserver/thegitrogserver.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
#gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
